@startuml Analisi
skinparam classAttributeIconSize 0

' classi
class Task <<final>> {
    - id: int
    - period: Duration
    - deadline: Duration
    - chunks: List<Chunk>
    - isExecuted: boolean
    - nominalPriority: int
    - dinamicPrioriy: int
    + execute(): Duration
    + checkAndReset(): void
}

class Chunk <<final>> {
    - id: int
    - executionTime: Duration
    - resource: Resource
    + execute(): void
    + reset(): void
}

class Taskset <<final>> {
    - tasks: Set<Task>
}

class Resource {
    - sempahore: Semaphore
}

abstract class Scheduler {
    - taskSet: Taskset
    - resAccProtocol: ResAccProtocol
    + schedule() <<abstract>>
}

class RMScheduler <<final>> {
    - checkPeriocity()
}

class EDFScheduler <<final>> {
}

abstract class ResAccProtocol {
}

class PriorityCeilingProtocol <<final>> {
}

class Semaphore{
    - ceiling: int
}

' relazioni
Task "1...*" *-- "1...*" Chunk
Taskset "1...*" *-- "1...*" Task
Chunk "*" *-- "*" Resource
Scheduler <|-- RMScheduler
Scheduler <|-- EDFScheduler
Scheduler "*" *-- "1" Taskset
ResAccProtocol <|-- PriorityCeilingProtocol
Scheduler "*" *-- "1" ResAccProtocol
Resource "1...*" *-- "1" Semaphore

@enduml