@startuml sequence diagram RM

participant Client
Scheduler -> Scheduler : reset
Scheduler -> Scheduler : assignPriority
Client -> Scheduler : schedule
Scheduler -> MyClock : reset
Scheduler -> Scheduler : initStructures
Scheduler -> Task : execute
Task -> ResourcesProtocol : access
Task -> ResourcesProtocol : progress
Task -> Chunk : execute
Task -> ResourcesProtocol : release
Scheduler -> MyClock : advanceTo
Scheduler -> Task : relasePeriodTasks
Task -> Chunk : reset
Scheduler --> Client : trace.log

@enduml