@startuml sequence diagram

participant Client
Scheduler -> Scheduler : assignPriority
Client -> Scheduler : schedule
Scheduler -> Scheduler : reset
Scheduler -> MyClock : reset
Scheduler -> Scheduler : initStructures
Scheduler -> Scheduler : realeaseAllTasks

loop there is event
Scheduler -> Task : execute
Task -> ResourcesProtocol : access
Task -> ResourcesProtocol : progress
Task -> Chunk : execute
Task -> ResourcesProtocol : release
Scheduler -> MyClock : advanceTo
Scheduler -> Task : relasePeriodTasks
end

Scheduler --> Client : trace.log

@enduml