package scheduler;

import java.time.Duration;
import java.util.List;
import java.util.Set;

import helper.ReflectionUtils;
import taskSet.Chunk;
import taskSet.Task;
import taskSet.TaskSet;

import org.junit.Before;
import org.junit.Test;

import exeptions.DeadlineMissedException;

import static org.assertj.core.api.Assertions.*;

public class RMSchedulerTest {

    private Chunk chunk;

    @Before
    public void setup() {
        this.chunk = new Chunk(0, Duration.ofSeconds(1));
    }

    @Test
    public void assignPriority() {
        Task task0 = new Task(
            Duration.ofSeconds(10),
            Duration.ofSeconds(10),
            List.of(this.chunk));
        Task task1 = new Task(
            Duration.ofSeconds(5),
            Duration.ofSeconds(5),
            List.of(this.chunk));
        Task task2 = new Task(
            Duration.ofSeconds(15),
            Duration.ofSeconds(15),
            List.of(this.chunk));
        assertThat(task0.getNominalPriority())
            .isEqualTo((int) ReflectionUtils.getField(task0, "dinamicPriority"))
            .isZero();
        assertThat(task1.getNominalPriority())
            .isEqualTo((int) ReflectionUtils.getField(task1, "dinamicPriority"))
            .isZero();
        assertThat(task2.getNominalPriority())
            .isEqualTo((int) ReflectionUtils.getField(task2, "dinamicPriority"))
            .isZero();
        new RMScheduler(new TaskSet(Set.of(task0, task1, task2)));
        assertThat(task1.getNominalPriority())
            .isEqualTo((int) ReflectionUtils.getField(task1, "dinamicPriority"))
            .isEqualTo(5);
        assertThat(task0.getNominalPriority())
            .isEqualTo((int) ReflectionUtils.getField(task0, "dinamicPriority"))
            .isEqualTo(7);
        assertThat(task2.getNominalPriority())
            .isEqualTo((int) ReflectionUtils.getField(task2, "dinamicPriority"))
            .isEqualTo(9);
    }

    @SuppressWarnings("unchecked")
    @Test
    public void relasePeriodTasks() throws Exception {
        Task task0 = new Task(
            Duration.ofSeconds(7),
            Duration.ofSeconds(7),
            List.of(this.chunk));
        Task task1 = new Task(
            Duration.ofSeconds(5),
            Duration.ofSeconds(5),
            List.of(this.chunk));
        ReflectionUtils.setField(task1, "isExecuted", true);
        Task task2 = new Task(
            Duration.ofSeconds(15),
            Duration.ofSeconds(15),
            List.of(this.chunk));
        TaskSet taskSet = new TaskSet(Set.of(task0, task1, task2));
        RMScheduler scheduler = new RMScheduler(taskSet);
        Duration currentTime = Duration.ofSeconds(10);

        List<Task> output = (List<Task>) ReflectionUtils.invokeMethod(
            scheduler,
            "relasePeriodTasks",
            new Class<?>[]{Duration.class},
            new Object[]{currentTime});
        assertThat(output)
            .containsExactly(task1);
    }

    // tested also with the trace generated by the scheduler
    @Test
    public void scheduleWOResourceOK() {
        Task task0 = new Task(
            Duration.ofSeconds(20),
            Duration.ofSeconds(20),
            List.of(
                new Chunk(1, Duration.ofSeconds(4))));
        Task task1 = new Task(
            Duration.ofSeconds(50),
            Duration.ofSeconds(50),
            List.of(
                new Chunk(1, Duration.ofSeconds(6)),
                new Chunk(2, Duration.ofSeconds(3)),
                new Chunk(3, Duration.ofSeconds(3))));
        Task task2 = new Task(
            Duration.ofSeconds(100),
            Duration.ofSeconds(100),
            List.of(
                new Chunk(1, Duration.ofSeconds(10))));
        TaskSet taskSet = new TaskSet(Set.of(task0, task1, task2));
        RMScheduler scheduler = new RMScheduler(taskSet);
        assertThatCode(() -> scheduler.schedule())
            .doesNotThrowAnyException();
    }

    // tested also with the trace generated by the scheduler
    @Test
    public void scheduleWOResourceKO() {
        Task task0 = new Task(
            Duration.ofSeconds(10),
            Duration.ofSeconds(10),
            List.of(
                new Chunk(1, Duration.ofSeconds(4))));
        Task task1 = new Task(
            Duration.ofSeconds(15),
            Duration.ofSeconds(15),
            List.of(
                new Chunk(1, Duration.ofSeconds(6)),
                new Chunk(2, Duration.ofSeconds(2))));
        TaskSet taskSet = new TaskSet(Set.of(task0, task1));
        RMScheduler scheduler = new RMScheduler(taskSet);
        assertThatThrownBy(() -> scheduler.schedule())
            .isInstanceOf(DeadlineMissedException.class)
            .hasMessageContaining("Il task " + task1.getId() + " ha superato la deadline");
    }
    
}